---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nextcloud-lb
  name: nextcloudapp-social
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: nextcloudapp
    spec:
      containers:
      - image: liontechacademy/apps:nextcloud-v1.0.0
        name: nextcloudapp
        ports:
        - name: nextcloudapp
          containerPort: 80 
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nextcloudapp-service
  name: nextcloudapp
spec:
  type: LoadBalancer  #loadBalancer or Loadbalancer 
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: nextcloudapp